from . import (
    ai,
    calendar,
    core,
    finance,
    fitness,
    garmin,
    habits,
    journal,
    news,
    nutrition,
    recovery,
    sleep,
    stocks,
    study,
    timetable,
    todos,
)

ROUTERS = [
    core.router,
    garmin.router,
    fitness.router,
    sleep.router,
    recovery.router,
    calendar.router,
    timetable.router,
    study.router,
    nutrition.router,
    habits.router,
    todos.router,
    journal.router,
    finance.router,
    stocks.router,
    news.router,
    ai.router,
]
